name: "PDE Task"
description: "Create a new task for PDE (non-policy work: scripts, tooling, initiatives, improvements)"
title: "[PDE] <Short task name>"
labels:
  - pde
  - task
  - feature
  - help wanted
body:
  - type: input
    id: assignee
    attributes:
      label: Assignee
      description: "GitHub username of the person responsible"
      placeholder: "@username"
    validations:
      required: true

  - type: input
    id: start_date
    attributes:
      label: Start Date
      description: "Format: YYYY-MM-DD"
      placeholder: "2025-01-01"
    validations:
      required: true

  - type: input
    id: end_date
    attributes:
      label: End Date (Target)
      description: "Format: YYYY-MM-DD"
      placeholder: "2025-01-15"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Explain the task, context, purpose, and impact"
      placeholder: "What is this task about?"
    validations:
      required: true

  - type: textarea
    id: objectives
    attributes:
      label: Objectives / Expected Outcome
      description: "Define what success looks like"
      placeholder: "- Improve script reliability\n- Produce documentation\n- Resolve workflow errors"

  - type: textarea
    id: steps
    attributes:
      label: Steps / Action Items
      description: "List the steps required to complete the task"
      placeholder: |
        1.  
        2.  
        3.  

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: "Other tasks, PRs, or teams this depends on"
      placeholder: "- PR #123\n- Waiting on external review"

  - type: textarea
    id: links
    attributes:
      label: Related Links
      description: "PRs, docs, Slack threads, references"
      placeholder: "- https://..."

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Not started
        - In progress
        - Blocked
        - Completed
    validations:
      required: true
